site_name: Scheduler for AID2E
site_description: A Python library for scheduling and managing optimization trials for the ePIC EIC detector design using Ax
site_author: AID2E Team
site_url: https://aid2e.github.io/scheduler_epic/
repo_url: https://github.com/aid2e/scheduler_epic
repo_name: aid2e/scheduler_epic

# GitHub repository information
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aid2e/scheduler_epic
      name: Scheduler on GitHub
  
  # Edit link to redirect to GitHub
  repo_icon: github
  edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # GitBook-like colors
    primary: white
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  features:
    # GitBook-like navigation
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    # GitHub integration
    - content.action.edit  # Adds "Edit this page" button
    - content.action.view  # Adds "View source" button
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/aid2e_logo.png
  favicon: assets/aid2e_logo.png

# Add custom CSS to make it more GitBook-like
extra_css:
  - stylesheets/gitbook.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Basic Detector Optimization: tutorials/detector_optimization.md
    - Slurm Execution: tutorials/slurm_execution.md
    - Container-Based Optimization: tutorials/container_based_optimization.md
    - Batch Trial Submission: tutorials/batch_trial_submission.md
  - API Reference:
    - Overview: api/index.md
    - AxScheduler: api/ax_scheduler.md
    - Trial: api/trial.md
    - Job: api/job.md
    - Runners: api/runners.md
  - Architecture: architecture.md
  - GitHub Pages Setup: github_pages_setup.md
