site_name: Scheduler for AID2E
site_description: A Python library for scheduling and managing optimization trials for the ePIC EIC detector design using Ax
site_author: AID2E Team
site_url: https://aid2e.github.io/scheduler_epic/
repo_url: https://github.com/aid2e/scheduler_epic
repo_name: aid2e/scheduler_epic

# Theme configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - search.highlight
    - search.suggest
    - navigation.tabs
    # add navigation sidebar features
    - navigation.tabs.sticky
    - navigation.tabs.sticky_header
    - navigation.tabs.instant
    - navigation.tabs.autohide
    - navigation.instant
    - header.autohide
  icon:
    repo: fontawesome/brands/github

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aid2e/scheduler_epic
      name: AID2E Scheduler on GitHub
  
  # Add GitHub edit capabilities
  repo_icon: github
  edit_uri: edit/main/docs/

# Add custom CSS to make it more GitBook-like
extra_css:
  - stylesheets/gitbook.css

# Markdown extensions for richer content
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

# Navigation structure
nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Basic Detector Optimization: tutorials/detector_optimization.md
    - Slurm Execution: tutorials/slurm_execution.md
    - Container-Based Optimization: tutorials/container_based_optimization.md
    - Container Jobs: tutorials/container_jobs.md
    - Batch Trial Submission: tutorials/batch_trial_submission.md
    - Script-Based Optimization: tutorials/script_based_optimization.md
    - PANDA Execution: tutorials/panda_execution.md
    - Asynchronous Execution: tutorials/asynchronous_execution.md
    - Experiment Persistence: tutorials/experiment_persistence.md
  - API Reference:
    - Overview: api/index.md
    - AxScheduler: api/ax_scheduler.md
    - Trial: api/trial.md
    - Job: api/job.md
    - Runners: api/runners.md
  - Architecture: architecture.md
  - Documentation:
    - GitHub Pages Setup: github_pages_setup.md
    - Step-by-Step Guide: step_by_step_guide.md
    - Deployment Options: deployment_options.md
    - API Documentation: api_documentation.md
  
# Plugins for additional functionality
plugins:
  - search
