site_name: Scheduler for AID2E
site_description: A Python library for scheduling and managing optimization trials for the ePIC EIC detector design using Ax
site_author: AID2E Team
repo_url: https://github.com/yourusername/scheduler
repo_name: yourusername/scheduler

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Basic Detector Optimization: tutorials/detector_optimization.md
    - Slurm Execution: tutorials/slurm_execution.md
    - Container-Based Optimization: tutorials/container_based_optimization.md
    - Batch Trial Submission: tutorials/batch_trial_submission.md
  - API Reference:
    - Overview: api/index.md
    - AxScheduler: api/ax_scheduler.md
    - Trial: api/trial.md
    - Job: api/job.md
    - Runners: api/runners.md
  - Architecture: architecture.md
  - GitHub Pages Setup: github_pages_setup.md
